### ISSUE TITLE
Why not to use `(e if e instanceof TypeError)` supported by Firefox ?

### ISSUE THREAD

**Issue by Yaffle** [benderTheCrime/error-type-specific-catch-proposal#1]
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/try...catch#Conditional_catch_clauses

**Comment by benderTheCrime** [comment]
@Yaffle This was also brought to my attention on the es-discuss mailing thread.

I was not aware of this non-standard implementation of type-specific catching. It definitely throws a wrench into this proposal.

I'm not sure what the committee's stance is on backward compatibility and non-standard features. It would be ideal if the spider monkey implementation could work while implementing a standard feature alongside.

As I mentioned on the mailing list, I find the SpiderMonkey implementation a little clunky/inconvinient. Instead of imposing an additional condition, I would rather have the engine understand that I am trying to catch a specific type of error simply by defining the error next to the catch keyword.

**Comment by benderTheCrime** [comment]
@Yaffle thanks for bringing this to my attention. I've addressed it here: https://github.com/benderTheCrime/error-type-specific-catch-proposal#about-spidermonkey-implementation

**Comment by Yaffle** [comment]
Thanks for the answer
